
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>NurseHotkey</AssemblyName>
    <LangVersion>latest</LangVersion>
    <FileUpgradeFlags>40</FileUpgradeFlags>
    <UpgradeBackupLocation>Z:\New Stuff\Replacement Library\Documents\my games\Terraria\tModLoader\ModSources\NurseHotkey\Backup\</UpgradeBackupLocation>
    <OldToolsVersion>2.0</OldToolsVersion>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Assets\Music\" />
    <Folder Include="Assets\Textures\" />
    <Folder Include="Assets\Sounds\" />
    <Folder Include="Content\" />
    <Folder Include="Common\" />
    <Folder Include="Localization\" />
    <Folder Include="Recipes\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BossChecklist">
      <HintPath>C:\Users\Graham\Desktop\terraria source code\BossChecklist.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>